.TH "/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/util/tools Directory Reference" 3 "Sun Mar 26 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/util/tools Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBPath\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPath\&.h\fP"
.br
.in -1c
