.TH "/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/gui Directory Reference" 3 "Sun Mar 26 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/gui Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBControl\&.cpp\fP"
.br
.ti -1c
.RI "file \fBControl\&.h\fP"
.br
.ti -1c
.RI "file \fBGlobalSettingsBar\&.h\fP"
.br
.ti -1c
.RI "file \fBHeatWidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHeatWidget\&.h\fP"
.br
.ti -1c
.RI "file \fBImportWindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBImportWindow\&.h\fP"
.br
.ti -1c
.RI "file \fBMainWidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMainWidget\&.h\fP"
.br
.ti -1c
.RI "file \fBMainWindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMainWindow\&.h\fP"
.br
.ti -1c
.RI "file \fBPlotWidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPlotWidget\&.h\fP"
.br
.ti -1c
.RI "file \fBPMWidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPMWidget\&.h\fP"
.br
.ti -1c
.RI "file \fBSignalPlot\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSignalPlot\&.h\fP"
.br
.ti -1c
.RI "file \fBSignalViewWidget\&.h\fP"
.br
.in -1c
