.TH "/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/amv/anc Directory Reference" 3 "Fri Mar 24 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/amv/anc Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBalgorithm\fP"
.br
.ti -1c
.RI "directory \fBmodel\fP"
.br
.ti -1c
.RI "directory \fBview\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBANCAlgorithmRegister\&.h\fP"
.br
.in -1c
