.TH "/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/amv/anc/ANCAlgorithmRegister.h" 3 "Sun Mar 26 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/amv/anc/ANCAlgorithmRegister.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include 'Code/UANC/amv/anc/algorithm/InverseDirectAlgorithm\&.h'\fP
.br
\fC#include 'Code/UANC/amv/anc/algorithm/InverseFFTAlgorithm\&.h'\fP
.br
\fC#include 'Code/UANC/amv/anc/algorithm/LinearExtrapolation\&.h'\fP
.br
\fC#include 'Code/UANC/amv/anc/algorithm/LocallyWeightedRegression\&.h'\fP
.br
\fC#include 'Code/UANC/amv/anc/algorithm/QuinticSplines\&.h'\fP
.br
\fC#include 'Code/UANC/amv/anc/algorithm/PolynomialRegression\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBuanc::amv::anc::ANCAlgorithmRegister\fP"
.br
.RI "\fIThis class is used to retain a list of all algorithms\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuanc\fP"
.br
.ti -1c
.RI " \fBuanc::amv\fP"
.br
.ti -1c
.RI " \fBuanc::amv::anc\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
