.TH "/ext/local/University/BP/Git/UANC/Code/UANC/amv/anc/model/ANCModel.h" 3 "Tue Mar 28 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/ext/local/University/BP/Git/UANC/Code/UANC/amv/anc/model/ANCModel.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Code/UANC/amv/InvertedModel\&.h>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <Code/UANC/util/PerformanceMeasure\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBuanc::amv::anc::model::ANCModel\fP"
.br
.RI "\fIThis is an \fBANCModel\fP\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuanc\fP"
.br
.ti -1c
.RI " \fBuanc::amv\fP"
.br
.ti -1c
.RI " \fBuanc::amv::anc\fP"
.br
.ti -1c
.RI " \fBuanc::amv::anc::model\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
