.TH "/ext/local/University/BP/Git/UANC/Code/UANC/amv/anc/view/ANCView.cpp" 3 "Tue Mar 28 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/ext/local/University/BP/Git/UANC/Code/UANC/amv/anc/view/ANCView.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Code/UANC/gui/PlotWidget\&.h>\fP
.br
\fC#include 'ANCView\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuanc\fP"
.br
.ti -1c
.RI " \fBuanc::amv\fP"
.br
.ti -1c
.RI " \fBuanc::amv::anc\fP"
.br
.ti -1c
.RI " \fBuanc::amv::anc::view\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
