.TH "EpsilonTests" 3 "Sun Mar 26 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EpsilonTests \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EpsilonTests\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEpsilonTests\fP ()"
.br
.RI "\fIThis class can be used to check all algorithm\&. \fP"
.ti -1c
.RI "void \fBrun\fP (std::string path)"
.br
.RI "\fIThis methode runs all algorithm\&. \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EpsilonTests::EpsilonTests ()"

.PP
This class can be used to check all algorithm\&. Gives a statistic for each algorithm\&. 
.SH "Member Function Documentation"
.PP 
.SS "void EpsilonTests::run (std::string path)"

.PP
This methode runs all algorithm\&. Runs all algorithm and test if average error is smaler than epsilon 

.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
