.TH "EpsilonTests" 3 "Fri Mar 24 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EpsilonTests \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EpsilonTests\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEpsilonTests\fP ()"
.br
.ti -1c
.RI "void \fBrun\fP (std::string path)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EpsilonTests::EpsilonTests ()"
Contructor 
.SH "Member Function Documentation"
.PP 
.SS "void EpsilonTests::run (std::string path)"


.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
