.TH "/ext/local/University/BP/Git/UANC/Code/UANC/util/event/Events.h" 3 "Tue Mar 28 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/ext/local/University/BP/Git/UANC/Code/UANC/util/event/Events.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuanc\fP"
.br
.ti -1c
.RI " \fBuanc::util\fP"
.br
.ti -1c
.RI " \fBuanc::util::event\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBuanc::util::event::Events\fP : uint8_t { \fBuanc::util::event::Events::Scroll\fP = 0, \fBuanc::util::event::Events::ChangeView\fP = 1, \fBuanc::util::event::Events::ChangeChannel\fP = 2, \fBuanc::util::event::Events::Last\fP = 3 }
.RI "\fIThis enumeration contains all events\&. \fP""
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
