.TH "/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/util/event/EventObserver.cpp" 3 "Sun Mar 26 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/util/event/EventObserver.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'EventObserver\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuanc\fP"
.br
.ti -1c
.RI " \fBuanc::util\fP"
.br
.ti -1c
.RI " \fBuanc::util::event\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
