.TH "/ext/local/University/BP/Git/UANC/Code/UANC/util/event/EventToken.cpp" 3 "Tue Mar 28 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/ext/local/University/BP/Git/UANC/Code/UANC/util/event/EventToken.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Code/UANC/util/GlobalSettings\&.h>\fP
.br
\fC#include 'EventToken\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuanc\fP"
.br
.ti -1c
.RI " \fBuanc::util\fP"
.br
.ti -1c
.RI " \fBuanc::util::event\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
