.TH "EventIDHash" 3 "Tue Mar 28 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EventIDHash \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EventManager\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T , typename U > std::size_t \fBoperator()\fP (const std::pair< T, U > &x) const "
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename T , typename U > std::size_t EventIDHash::operator() (const std::pair< T, U > & x) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
