.TH "EventIDEqual" 3 "Sun Mar 26 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EventIDEqual \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EventManager\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T , typename U > bool \fBoperator()\fP (std::pair< T, U > const &t1, std::pair< T, U > const &t2) const "
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename T , typename U > bool EventIDEqual::operator() (std::pair< T, U > const & t1, std::pair< T, U > const & t2) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
