.TH "/ext/local/University/BP/Git/UANC/Code/UANC/util/event/EventToken.h" 3 "Tue Mar 28 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/ext/local/University/BP/Git/UANC/Code/UANC/util/event/EventToken.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include 'Events\&.h'\fP
.br
\fC#include 'EventContainer\&.h'\fP
.br
\fC#include 'EventManager\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBuanc::util::event::EventToken\fP"
.br
.RI "\fIToken retrieved by the eventsystem\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuanc\fP"
.br
.ti -1c
.RI " \fBuanc::util\fP"
.br
.ti -1c
.RI " \fBuanc::util::event\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
