.TH "/ext/local/University/BP/Git/UANC/Code/UANC/amv/signal/algorithm/FFTTransformationAlgorithm.h" 3 "Tue Mar 28 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/ext/local/University/BP/Git/UANC/Code/UANC/amv/signal/algorithm/FFTTransformationAlgorithm.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Code/UANC/amv/signal/algorithm/SignalTransformationAlgorithm\&.h>\fP
.br
\fC#include <Code/UANC/amv/signal/model/FFTModel\&.h>\fP
.br
\fC#include <Code/UANC/amv/signal/view/FFTView\&.h>\fP
.br
\fC#include <Code/libs/aquila/source/SignalSource\&.h>\fP
.br
\fC#include <Code/libs/aquila/transform/FftFactory\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBuanc::amv::signal::algorithm::FFTTransformationAlgorithm\fP"
.br
.RI "\fITransforms the view of a signal into Fourier space using FFT\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuanc\fP"
.br
.ti -1c
.RI " \fBuanc::amv\fP"
.br
.ti -1c
.RI " \fBuanc::amv::signal\fP"
.br
.ti -1c
.RI " \fBuanc::amv::signal::algorithm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
