.TH "/ext/local/University/BP/Git/UANC/Code/UANC/amv/signal/view/FFTView.h" 3 "Tue Mar 28 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/ext/local/University/BP/Git/UANC/Code/UANC/amv/signal/view/FFTView.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include <QtWidgets/QWidget>\fP
.br
\fC#include <Code/UANC/amv/InvertedModel\&.h>\fP
.br
\fC#include <Code/UANC/amv/AlgorithmView\&.h>\fP
.br
\fC#include <Code/UANC/gui/PlotWidget\&.h>\fP
.br
\fC#include <Code/UANC/amv/signal/model/FFTModel\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBuanc::amv::signal::view::FFTView\fP"
.br
.RI "\fIRepresents a \fBSignalView\fP\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuanc\fP"
.br
.ti -1c
.RI " \fBuanc::amv\fP"
.br
.ti -1c
.RI " \fBuanc::amv::signal\fP"
.br
.ti -1c
.RI " \fBuanc::amv::signal::view\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
