.TH "/ext/local/University/BP/Git/UANC/Code/UANC/gui/HeatWidget.cpp" 3 "Tue Mar 28 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/ext/local/University/BP/Git/UANC/Code/UANC/gui/HeatWidget.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'HeatWidget\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
