.TH "/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/amv/signal/algorithm/IdentityTransformationAlgorithm.h" 3 "Sun Mar 26 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/amv/signal/algorithm/IdentityTransformationAlgorithm.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Code/UANC/amv/anc/model/ANCModel\&.h>\fP
.br
\fC#include <Code/UANC/amv/anc/view/ANCView\&.h>\fP
.br
\fC#include <Code/UANC/amv/signal/view/SignalView\&.h>\fP
.br
\fC#include 'SignalTransformationAlgorithm\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBuanc::amv::signal::algorithm::IdentityTransformationAlgorithm\fP"
.br
.RI "\fIIdentity transformation\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuanc\fP"
.br
.ti -1c
.RI " \fBuanc::amv\fP"
.br
.ti -1c
.RI " \fBuanc::amv::signal\fP"
.br
.ti -1c
.RI " \fBuanc::amv::signal::algorithm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
