.TH "/ext/local/University/BP/Git/UANC/Code/UANC/gui/ImportWindow.h" 3 "Tue Mar 28 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/ext/local/University/BP/Git/UANC/Code/UANC/gui/ImportWindow.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <unordered_map>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include <QSignalMapper>\fP
.br
\fC#include <QFileInfo>\fP
.br
\fC#include <QtCore/QVariant>\fP
.br
\fC#include <QAction>\fP
.br
\fC#include <QApplication>\fP
.br
\fC#include <QButtonGroup>\fP
.br
\fC#include <QCheckBox>\fP
.br
\fC#include <QComboBox>\fP
.br
\fC#include <QGroupBox>\fP
.br
\fC#include <QHBoxLayout>\fP
.br
\fC#include <QHeaderView>\fP
.br
\fC#include <QLineEdit>\fP
.br
\fC#include <QMainWindow>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QScrollArea>\fP
.br
\fC#include <QStatusBar>\fP
.br
\fC#include <QVBoxLayout>\fP
.br
\fC#include <QWidget>\fP
.br
\fC#include 'Code/UANC/util/DialogUtil\&.h'\fP
.br
\fC#include 'Code/UANC/gui/MainWindow\&.h'\fP
.br
\fC#include 'Code/libs/aquila/source/SignalSource\&.h'\fP
.br
\fC#include 'Code/UANC/util/SignalManager\&.h'\fP
.br
\fC#include 'Code/UANC/util/SignalFileActor\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBuanc::gui::ImportWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuanc\fP"
.br
.ti -1c
.RI " \fBuanc::gui\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
