.TH "/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/amv/anc/algorithm/InverseDirectAlgorithm.h" 3 "Sun Mar 26 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/amv/anc/algorithm/InverseDirectAlgorithm.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Code/UANC/amv/anc/model/ANCModel\&.h>\fP
.br
\fC#include <Code/UANC/amv/anc/view/ANCView\&.h>\fP
.br
\fC#include <Code/UANC/amv/anc/view/PMView\&.h>\fP
.br
\fC#include <Code/UANC/util/PerformanceMeasure\&.h>\fP
.br
\fC#include 'ANCAlgorithm\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBuanc::amv::anc::algorithm::InverseDirectAlgorithm\fP"
.br
.RI "\fIDirect inversion algorithm\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuanc\fP"
.br
.ti -1c
.RI " \fBuanc::amv\fP"
.br
.ti -1c
.RI " \fBuanc::amv::anc\fP"
.br
.ti -1c
.RI " \fBuanc::amv::anc::algorithm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
