.TH "/ext/local/University/BP/Git/UANC/Code/UANC/amv/anc/algorithm/LinearExtrapolation.h" 3 "Tue Mar 28 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/ext/local/University/BP/Git/UANC/Code/UANC/amv/anc/algorithm/LinearExtrapolation.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBuanc::amv::anc::algorithm::LinearExtrapolation\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuanc\fP"
.br
.ti -1c
.RI " \fBuanc::amv\fP"
.br
.ti -1c
.RI " \fBuanc::amv::anc\fP"
.br
.ti -1c
.RI " \fBuanc::amv::anc::algorithm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
