.TH "/ext/local/University/BP/Git/UANC/Code/UANC/main.cpp" 3 "Tue Mar 28 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/ext/local/University/BP/Git/UANC/Code/UANC/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Code/UANC/gui/MainWindow\&.h>\fP
.br
\fC#include <Code/UANC/util/GlobalSettings\&.h>\fP
.br
\fC#include <Code/UANC/util/tests/EpsilonTests\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
