.TH "/ext/local/University/BP/Git/UANC/Code/UANC/gui/MainWindow.h" 3 "Tue Mar 28 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/ext/local/University/BP/Git/UANC/Code/UANC/gui/MainWindow.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <QApplication>\fP
.br
\fC#include <QMenuBar>\fP
.br
\fC#include <QtWidgets/QMainWindow>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <QtWidgets/QVBoxLayout>\fP
.br
\fC#include <QtWidgets/QLabel>\fP
.br
\fC#include 'MainWidget\&.h'\fP
.br
\fC#include 'Code/libs/aquila/source/SignalSource\&.h'\fP
.br
\fC#include 'Code/UANC/util/SignalManager\&.h'\fP
.br
\fC#include 'ImportWindow\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBuanc::gui::MainWindow\fP"
.br
.RI "\fIThis class represents the main window\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuanc\fP"
.br
.ti -1c
.RI " \fBuanc::gui\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
