.TH "/ext/local/University/BP/Git/UANC/Code/UANC/gui/MainWidget.cpp" 3 "Tue Mar 28 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/ext/local/University/BP/Git/UANC/Code/UANC/gui/MainWidget.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Code/UANC/util/tools/Path\&.h>\fP
.br
\fC#include <Code/libs/aquila/source/WaveFile\&.h>\fP
.br
\fC#include <Code/UANC/amv/anc/algorithm/InverseFFTAlgorithm\&.h>\fP
.br
\fC#include <Code/UANC/amv/anc/ANCAlgorithmRegister\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <Code/UANC/util/GlobalSettings\&.h>\fP
.br
\fC#include 'MainWidget\&.h'\fP
.br
\fC#include 'SignalViewWidget\&.h'\fP
.br
\fC#include 'GlobalSettingsBar\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuanc\fP"
.br
.ti -1c
.RI " \fBuanc::gui\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBuanc::gui::tabInRun\fP = false"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
