.TH "/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/gui/MainWidget.h" 3 "Sun Mar 26 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/gui/MainWidget.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include <QtWidgets/QWidget>\fP
.br
\fC#include <QtWidgets/QVBoxLayout>\fP
.br
\fC#include <QtWidgets/QPushButton>\fP
.br
\fC#include <Code/libs/qprogressindicator/QProgressIndicator\&.h>\fP
.br
\fC#include 'Code/UANC/amv/Algorithm\&.h'\fP
.br
\fC#include 'Code/UANC/amv/AlgorithmThread\&.h'\fP
.br
\fC#include 'Code/UANC/amv/anc/algorithm/InverseDirectAlgorithm\&.h'\fP
.br
\fC#include 'Code/UANC/util/SignalManager\&.h'\fP
.br
\fC#include 'PlotWidget\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBuanc::gui::MainWidget\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuanc\fP"
.br
.ti -1c
.RI " \fBuanc::gui\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
