.TH "/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/gui/PlotWidget.h" 3 "Fri Mar 24 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/gui/PlotWidget.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtWidgets/QWidget>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <Code/UANC/amv/InvertedModel\&.h>\fP
.br
\fC#include <Code/UANC/util/event/EventObserver\&.h>\fP
.br
\fC#include 'SignalPlot\&.h'\fP
.br
\fC#include 'Control\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBuanc::gui::PlotWidget\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuanc\fP"
.br
.ti -1c
.RI " \fBuanc::gui\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
