.TH "/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/gui/PMWidget.h" 3 "Sun Mar 26 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/gui/PMWidget.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Code/libs/aquila/source/SignalSource\&.h>\fP
.br
\fC#include <QtWidgets/QWidget>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <Code/UANC/util/PerformanceMeasure\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBuanc::gui::PMWidget\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuanc\fP"
.br
.ti -1c
.RI " \fBuanc::gui\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
