.TH "/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/amv/SignalModel.h" 3 "Sun Mar 26 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/amv/SignalModel.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Code/libs/aquila/source/SignalSource\&.h>\fP
.br
\fC#include 'Code/UANC/amv/PerformanceMeasurementRegister\&.h'\fP
.br
\fC#include <memory>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBuanc::amv::SignalModel\fP"
.br
.RI "\fIEvery model used inside of this application has to be a signal model\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuanc\fP"
.br
.ti -1c
.RI " \fBuanc::amv\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
