.TH "/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/amv/signal/view/SignalView.cpp" 3 "Fri Mar 24 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/amv/signal/view/SignalView.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Code/UANC/gui/PlotWidget\&.h>\fP
.br
\fC#include 'SignalView\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuanc\fP"
.br
.ti -1c
.RI " \fBuanc::amv\fP"
.br
.ti -1c
.RI " \fBuanc::amv::signal\fP"
.br
.ti -1c
.RI " \fBuanc::amv::signal::view\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
