.TH "/ext/local/University/BP/Git/UANC/Code/UANC/amv/signal/model/SpectrogramModel.h" 3 "Tue Mar 28 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/ext/local/University/BP/Git/UANC/Code/UANC/amv/signal/model/SpectrogramModel.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Code/UANC/amv/InvertedModel\&.h>\fP
.br
\fC#include 'Code/libs/aquila/transform/Spectrogram\&.h'\fP
.br
\fC#include <memory>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBuanc::amv::signal::model::SpectrogramModel\fP"
.br
.RI "\fIThis is a model for the transformation of a signal to a spectrogram representation\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuanc\fP"
.br
.ti -1c
.RI " \fBuanc::amv\fP"
.br
.ti -1c
.RI " \fBuanc::amv::signal\fP"
.br
.ti -1c
.RI " \fBuanc::amv::signal::model\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
