.TH "/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/amv/signal/algorithm/SpectrogramTransformationAlgorithm.h" 3 "Fri Mar 24 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/amv/signal/algorithm/SpectrogramTransformationAlgorithm.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Code/UANC/amv/signal/model/SpectrogramModel\&.h>\fP
.br
\fC#include <Code/UANC/amv/signal/view/HeatView\&.h>\fP
.br
\fC#include 'Code/libs/aquila/transform/Spectrogram\&.h'\fP
.br
\fC#include 'Code/libs/aquila/source/FramesCollection\&.h'\fP
.br
\fC#include 'SignalTransformationAlgorithm\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBuanc::amv::signal::algorithm::SpectrogramTransformationAlgorithm\fP"
.br
.RI "\fITransforms the view of a signal into a spectrogram\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuanc\fP"
.br
.ti -1c
.RI " \fBuanc::amv\fP"
.br
.ti -1c
.RI " \fBuanc::amv::signal\fP"
.br
.ti -1c
.RI " \fBuanc::amv::signal::algorithm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
