.TH "/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/amv/signal/TransformationAlgorithmRegister.h" 3 "Fri Mar 24 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/kurt/Documents/Studium/Bachelor_Praktikum/UANC/Code/UANC/amv/signal/TransformationAlgorithmRegister.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include 'Code/UANC/amv/signal/algorithm/IdentityTransformationAlgorithm\&.h'\fP
.br
\fC#include 'Code/UANC/amv/signal/algorithm/SpectrogramTransformationAlgorithm\&.h'\fP
.br
\fC#include 'Code/UANC/amv/signal/algorithm/FFTTransformationAlgorithm\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBuanc::amv::signal::TransformationAlgorithmRegister\fP"
.br
.RI "\fIThis class is used to retain a list of all transformation\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuanc\fP"
.br
.ti -1c
.RI " \fBuanc::amv\fP"
.br
.ti -1c
.RI " \fBuanc::amv::signal\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
