.TH "uanc::gui::ImportWindow" 3 "Fri Mar 24 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uanc::gui::ImportWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ImportWindow\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBindicesLoaded\fP (std::vector< int > loadedIndices)"
.br
.RI "\fI: Slot that indicates that signals have been selected and loaded successfully into the SignalManager \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImportWindow\fP (QWidget *parent)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "uanc::gui::ImportWindow::ImportWindow (QWidget * parent)"
The default constructor 
.SH "Member Function Documentation"
.PP 
.SS "void uanc::gui::ImportWindow::indicesLoaded (std::vector< int > loadedIndices)\fC [signal]\fP"

.PP
: Slot that indicates that signals have been selected and loaded successfully into the SignalManager 

.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
