.TH "uanc::util::event" 3 "Sun Mar 26 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uanc::util::event \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEventContainer\fP"
.br
.RI "\fIThis is the event container\&. \fP"
.ti -1c
.RI "class \fBEventManager\fP"
.br
.RI "\fISimple event manager\&. \fP"
.ti -1c
.RI "class \fBEventObserver\fP"
.br
.RI "\fIRepresents the observer interface\&. \fP"
.ti -1c
.RI "class \fBEventToken\fP"
.br
.RI "\fIToken retrieved by the eventsystem\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBCache\fP = std::unordered_map< std::pair< int, \fBEvents\fP >, \fBEventContainer\fP, \fBEventIDHash\fP >"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBEvents\fP : uint8_t { \fBEvents::Scroll\fP = 0, \fBEvents::ChangeView\fP = 1, \fBEvents::ChangeChannel\fP = 2, \fBEvents::Last\fP = 3 }
.RI "\fIThis enumeration contains all events\&. \fP""
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBuanc::util::event::Cache\fP = typedef std::unordered_map<std::pair<int, \fBEvents\fP>, \fBEventContainer\fP, \fBEventIDHash\fP>"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBuanc::util::event::Events\fP : uint8_t\fC [strong]\fP"

.PP
This enumeration contains all events\&. These events get used by the event system to signal the current event\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIScroll \fP\fP
Gets fired when a view gets scrolled\&. Event describes when a widget gets scrolled\&. 
.TP
\fB\fIChangeView \fP\fP
Represents the change of a view\&. 
.TP
\fB\fIChangeChannel \fP\fP
Represents the change of a channel\&. 
.TP
\fB\fILast \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
