.TH "uanc::amv::InvertedModel" 3 "Sun Mar 26 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uanc::amv::InvertedModel \- This is an \fBInvertedModel\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <InvertedModel\&.h>\fP
.PP
Inherits \fBuanc::amv::SignalModel\fP\&.
.PP
Inherited by \fBuanc::amv::anc::model::ANCModel\fP, \fBuanc::amv::signal::model::FFTModel\fP, and \fBuanc::amv::signal::model::SpectrogramModel\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBSignalModel\fP > \fBinverted\fP = NULL"
.br
.RI "\fIHolds the inverted signal\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This is an \fBInvertedModel\fP\&. 

This model gets derived from the \fBSignalModel\fP\&. It adds a field containing the inverted signal to the original signal in \fBSignalModel\fP\&. 
.SH "Member Data Documentation"
.PP 
.SS "std::shared_ptr<\fBSignalModel\fP> uanc::amv::InvertedModel::inverted = NULL"

.PP
Holds the inverted signal\&. This field gets used, to save the inverted signal, in addition to the original signal, which is placed in the parent class \fBSignalModel\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
