.TH "uanc::amv::signal::algorithm" 3 "Fri Mar 24 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uanc::amv::signal::algorithm \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFFTTransformationAlgorithm\fP"
.br
.RI "\fITransforms the view of a signal into Fourier space using FFT\&. \fP"
.ti -1c
.RI "class \fBIdentityTransformationAlgorithm\fP"
.br
.RI "\fIIdentity transformation\&. \fP"
.ti -1c
.RI "class \fBSignalTransformationAlgorithm\fP"
.br
.RI "\fIEvery algorithm used inside has to be derived by this class\&. \fP"
.ti -1c
.RI "class \fBSpectrogramTransformationAlgorithm\fP"
.br
.RI "\fITransforms the view of a signal into a spectrogram\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
