.TH "uanc::amv::anc" 3 "Sun Mar 26 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uanc::amv::anc \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBalgorithm\fP"
.br
.ti -1c
.RI " \fBmodel\fP"
.br
.ti -1c
.RI " \fBview\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBANCAlgorithmRegister\fP"
.br
.RI "\fIThis class is used to retain a list of all algorithms\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
