.TH "uanc::amv::anc::model" 3 "Sun Mar 26 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uanc::amv::anc::model \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBANCModel\fP"
.br
.RI "\fIThis is an \fBANCModel\fP\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
