.TH "uanc::amv::anc::view" 3 "Fri Mar 24 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uanc::amv::anc::view \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBANCView\fP"
.br
.RI "\fIRepresents an \fBANCView\fP\&. \fP"
.ti -1c
.RI "class \fBPMView\fP"
.br
.RI "\fIRepresents an \fBPMView\fP\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
