.TH "uanc::util::GlobalSettings" 3 "Fri Mar 24 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uanc::util::GlobalSettings \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GlobalSettings\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBGlobalSettings\fP * \fBget\fP ()"
.br
.RI "\fIThe default Constructor\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcurrentIndex\fP = 0"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBGlobalSettings\fP * \fBglobalSettings\fP = nullptr"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static \fBGlobalSettings\fP* uanc::util::GlobalSettings::get ()\fC [inline]\fP, \fC [static]\fP"

.PP
The default Constructor\&. 
.SH "Member Data Documentation"
.PP 
.SS "int uanc::util::GlobalSettings::currentIndex = 0"

.SS "\fBGlobalSettings\fP * GlobalSettings::globalSettings = nullptr\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
