.TH "uanc::util::Path" 3 "Fri Mar 24 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uanc::util::Path \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Path\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBgetFileName\fP (std::string path)"
.br
.RI "\fIPasses back the filename of the given path\&. \fP"
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "std::string uanc::util::Path::getFileName (std::string path)\fC [static]\fP"

.PP
Passes back the filename of the given path\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
