.TH "uanc::gui::MainWindow" 3 "Tue Mar 28 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uanc::gui::MainWindow \- This class represents the main window\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MainWindow\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBMainWindow\fP * \fBget\fP ()"
.br
.RI "\fIHol a reference to the main window\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBcloseEvent\fP (QCloseEvent *)"
.br
.RI "\fIThis method executes all necessary actions when the main application is closed\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class represents the main window\&. 

It is a QMainWindow\&. So you can think of it as a wrapper to extend the functionality of a basic QMainWindow 
.SH "Member Function Documentation"
.PP 
.SS "void uanc::gui::MainWindow::closeEvent (QCloseEvent *)\fC [protected]\fP"

.PP
This method executes all necessary actions when the main application is closed\&. It executes all necessary actions when the main application is closed 
.SS "\fBMainWindow\fP * uanc::gui::MainWindow::get ()\fC [static]\fP"

.PP
Hol a reference to the main window\&. Obtain a reference to the main window\&.
.PP
Uses a classical singleton pattern to give back exactly the same copy of the main window\&. In addition it uses a shared pointer\&.
.PP
\fBReturns:\fP
.RS 4
The shared pointer containing the \fBMainWindow\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
