.TH "uanc::amv::signal::view" 3 "Fri Mar 24 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uanc::amv::signal::view \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFFTView\fP"
.br
.RI "\fIRepresents a \fBSignalView\fP\&. \fP"
.ti -1c
.RI "class \fBHeatView\fP"
.br
.ti -1c
.RI "class \fBSignalView\fP"
.br
.RI "\fIRepresents a \fBSignalView\fP\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
