.TH "uanc::util" 3 "Sun Mar 26 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uanc::util \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBevent\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDialogUtil\fP"
.br
.RI "\fIThis class can be used to access various dialogs\&. \fP"
.ti -1c
.RI "class \fBDummyActor\fP"
.br
.ti -1c
.RI "class \fBFileActor\fP"
.br
.RI "\fISimple \fBFileActor\fP class, which can operate on a file\&. \fP"
.ti -1c
.RI "class \fBGlobalSettings\fP"
.br
.ti -1c
.RI "class \fBPath\fP"
.br
.ti -1c
.RI "class \fBPerformanceMeasure\fP"
.br
.ti -1c
.RI "class \fBPerformanceMeasureNode\fP"
.br
.ti -1c
.RI "class \fBSignalFileActor\fP"
.br
.RI "\fIBasic Signal file loader class\&. \fP"
.ti -1c
.RI "class \fBSignalManager\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBRunningState\fP { \fBRunningState::running\fP = true, \fBRunningState::stopped\fP = false }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBuanc::util::RunningState\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIrunning \fP\fP
.TP
\fB\fIstopped \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
