.TH "uanc::amv::anc::algorithm" 3 "Fri Mar 24 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uanc::amv::anc::algorithm \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBANCAlgorithm\fP"
.br
.RI "\fIEvery algorithm used inside has to be derived by this class\&. \fP"
.ti -1c
.RI "class \fBInverseDirectAlgorithm\fP"
.br
.RI "\fIDirect inversion algorithm\&. \fP"
.ti -1c
.RI "class \fBInverseFFTAlgorithm\fP"
.br
.RI "\fIFFT inversion algorithm\&. \fP"
.ti -1c
.RI "class \fBLinearExtrapolation\fP"
.br
.ti -1c
.RI "class \fBSplineInterpolation\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
