.TH "uanc::gui" 3 "Sun Mar 26 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uanc::gui \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBControl\fP"
.br
.ti -1c
.RI "class \fBGlobalSettingsBar\fP"
.br
.ti -1c
.RI "class \fBHeatWidget\fP"
.br
.ti -1c
.RI "class \fBImportWindow\fP"
.br
.ti -1c
.RI "class \fBMainWidget\fP"
.br
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.RI "\fIThis class represents the main window\&. \fP"
.ti -1c
.RI "class \fBPlotWidget\fP"
.br
.ti -1c
.RI "class \fBPMWidget\fP"
.br
.ti -1c
.RI "class \fBSignalPlot\fP"
.br
.ti -1c
.RI "class \fBSignalViewWidget\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBtabInRun\fP = false"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "bool uanc::gui::tabInRun = false"

.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
