.TH "uanc::amv" 3 "Fri Mar 24 2017" "Version 0.1" "UANC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uanc::amv \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBanc\fP"
.br
.ti -1c
.RI " \fBPMRegister\fP"
.br
.ti -1c
.RI " \fBsignal\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAlgorithm\fP"
.br
.RI "\fIThis is an algorithm used for defining more specific algorithms\&. \fP"
.ti -1c
.RI "class \fBAlgorithmThread\fP"
.br
.ti -1c
.RI "class \fBAlgorithmView\fP"
.br
.RI "\fIBasic algorithm associated view\&. \fP"
.ti -1c
.RI "class \fBIAlgorithm\fP"
.br
.RI "\fIGeneral interface for any algorithm\&. \fP"
.ti -1c
.RI "class \fBIAlgorithmView\fP"
.br
.RI "\fIThe general interface for every view\&. \fP"
.ti -1c
.RI "class \fBInvertedModel\fP"
.br
.RI "\fIThis is an \fBInvertedModel\fP\&. \fP"
.ti -1c
.RI "class \fBSignalModel\fP"
.br
.RI "\fIEvery model used inside of this application has to be a signal model\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UANC from the source code\&.
